---
version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: betting
      MYSQL_USER: betting
      MYSQL_PASSWORD: betting
      MYSQL_DATABASE: betting
    command: mysqld --default-authentication-plugin=mysql_native_password
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  maildev:
    image: djfarrelly/maildev
    ports:
      - "5005:80"
      - "1025:25"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    image: ccbb-backend
    ports:
      - "5000:5000"
    tty:
      true
    links:
      - mysql
      - maildev
    depends_on:
      - mysql
      - maildev

  frontend:
    container_name: frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ccbb-frontend
    ports:
      - "3000:3000"
    tty:
      true
    links:
      - backend
