---
version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: betting
      MYSQL_USER: betting
      MYSQL_PASSWORD: betting
      MYSQL_DATABASE: betting
    tty: true
    network_mode: bridge
